### ISSUE TITLE
Problem in new version

### ISSUE THREAD

**Issue by mgmcmk** [AplhaSlayer1964/kemono-dl#31] opened 2021-12-07 14:06 UTC
### Version

Version: 2021.12.06

### Service, User ID, Post ID

- Service: fanbox
- User ID: 17332140
- Post ID: 3060552

### Your Command
```bash
python kemono-dl.py --cookies "kemono.party_cookies.txt" --ignore-errors --archive archive.txt --force-indexing --force-inline --retry-download 1 --favorite-users --skip-filetypes psd,pdf,clip
```

### Description of bug

I guess, If the json data cannot be imported, the user name is specified as 'None' and the file is saved in a different location from the existing folder.

### How To Reproduce

After favorite several artists, use the '--favorite-users' option and download until a bug occurs.

### Error messages and tracebacks

Only the part where the error occurred is extracted.
```python

[info] Downloading User: None
[info] service: [fanbox] user_id: [17332140]
[Downloading] User icon.
[Downloading] User banner.
[info] Downloading Post: みくえっち
[info] service: [fanbox] user_id: [17332140] post_id: [3060552]
[info] Downloading attachments:
[Downloading] [1]_29fc08c1-ad3e-422a-af2d-5a679e465446.jpg
[==================================================] 4.7/4.7 MB, 0.7 MB/s
[Downloading] [2]_5cad06b2-88ae-49ee-bb40-73430a426544.jpg
[==================================================] 4.7/4.7 MB, 0.3 MB/s
[Downloading] [3]_233b77ac-7894-41e4-9544-dc10d9443bcf.jpg
[==================================================] 4.7/4.7 MB, 0.5 MB/s
[Downloading] [4]_aecef81b-94d8-445a-b53e-3d68d0161baa.jpg
[==================================================] 4.7/4.7 MB, 0.3 MB/s
[Downloading] [5]_baabf48c-5ba5-4d70-9fa4-c47d08541196.jpg
[==================================================] 4.7/4.7 MB, 0.3 MB/s
[Downloading] [6]_1553e82b-5274-4a76-8c56-488e13bd5566.jpg
[==================================================] 4.7/4.7 MB, 0.5 MB/s
[Downloading] [7]_cb3301fc-f6d6-4100-9ed7-aa4d03467761.jpg
[==================================================] 4.7/4.7 MB, 0.2 MB/s
[info] Wrong file type skiping download for "[8]_MayoMikuPSD_46.psd"
[Downloading] [9]_MayoMikuZIP_46.zip
[==================================================] 27.7/27.7 MB, 0.3 MB/s
[info] Downloading post file:
[Downloading] 47b5456f-fe2a-4b04-8392-f1d68fc5cde2.jpg
[==================================================] 0.2/0.2 MB, 0.5 MB/s
[info] Saving content: content.html
[info] Downloading inline images:
[info] Saving comments: comments.html
[info] Saving json: 3060552.json
[info] Completed downloading post: みくえっち
----------------------------------------------------------------------------------------------------
```

### Additional comments

![image](https://user-images.githubusercontent.com/8914838/145043618-aa025840-9c1a-4dd7-970c-1bdb64df6c4a.png)

**Comment by AplhaSlayer1964** [comment] 2021-12-07 19:49
The errors I can't reproduce are always the most annoying to fix. I pushed a new release that should fix it. I think somehow you are not getting a json object back from the request. I made the request header now request specifically a json object. If it fails 10 times it will print the last response header. If that happens please post the response header hear please. If that still doesn't help me figure out the problem I might make it dump the response contents to a file and have you send that.

**Comment by AplhaSlayer1964** [comment] 2021-12-19 23:53
I will assume the fix worked so I will be closing this issue.

**Closed by AplhaSlayer1964** 2021-12-19 23:53 UTC
Labels: bug
